"""AISC callout matching against the estimator's own shape table
(sidecar/aisc-shapes.json, generated by scripts/export-aisc-shapes.mjs).

find_callouts(text) yields regex hits; resolve(fam, dims) turns a hit into the
estimator's key ('W8x21', 'HSS6x6x3/8') with a confidence, or None."""
import difflib
import json
import re
from fractions import Fraction
from pathlib import Path

_DB = None
_INDEX = None


def load_db(path=None):
    global _DB, _INDEX
    path = Path(path or Path(__file__).with_name("aisc-shapes.json"))
    _DB = json.loads(path.read_text())
    _INDEX = {norm(k): k for k in _DB}
    return _DB


def db():
    return _DB if _DB is not None else load_db()


_NUM = r"[0-9]+(?:\s*-\s*[0-9]+/[0-9]+|\s+[0-9]+/[0-9]+|/[0-9]+)?(?:\.[0-9]+)?|\.[0-9]+"
_SEP = r"\s*[xX\u00d7]\s*"
CALLOUT = re.compile(
    rf"(?<![A-Z0-9])(HSS|MC|WT|HP|PIPE|PL|W|C|L)\s*({_NUM}){_SEP}({_NUM})(?:{_SEP}({_NUM}))?(?![0-9/])",
    re.I,
)
_VULGAR = {"\u00bc": "1/4", "\u00bd": "1/2", "\u00be": "3/4", "\u215b": "1/8", "\u215c": "3/8",
           "\u215d": "5/8", "\u215e": "7/8", "\u2153": "1/3", "\u2154": "2/3"}


def clean(text):
    for k, v in _VULGAR.items():
        text = text.replace(k, " " + v)
    return text.replace("\u00d7", "x").replace("\u2013", "-").replace("\u2014", "-")


def norm(s):
    """Comparison form: upper, no whitespace."""
    return re.sub(r"\s+", "", clean(s)).upper()


def _to_fraction(tok):
    """'0.375' -> '3/8'; '3/8' stays; '1 1/2' -> '1-1/2'; '21' stays."""
    tok = tok.strip()
    if re.fullmatch(r"[0-9]*\.[0-9]+", tok):
        f = Fraction(tok).limit_denominator(16)
        if f.denominator == 1:
            return str(f.numerator)
        whole, rem = divmod(f.numerator, f.denominator)
        return f"{whole}-{rem}/{f.denominator}" if whole else f"{rem}/{f.denominator}"
    return re.sub(r"\s*-\s*|\s+", "-", tok)


# Open-web steel joists (SJI): depth + series + section, e.g. 20LH04, 24K4,
# 24LHSP (special, weight from the joist supplier).  Approximate lb/ft from
# the SJI load tables; LHSP/DLH specials carry no weight until quoted.
# K / LH / DLH always carry a section number (24K4, 20LH06); the specials
# (LHSP, DLHSP, KCS) may not.  "12K" alone is a dimension fragment, not a joist.
JOIST = re.compile(r"(?<![A-Z0-9.])(\d{1,2}(?:\.5)?)\s?(?:(LHSP|DLHSP|KCS)(\d{1,2})?|(DLH|LH|K)\s?(\d{1,2}))(?![A-Z0-9/.])", re.I)
JOIST_WEIGHTS = {
    "8K1": 5.1, "10K1": 5.0, "12K1": 5.0, "12K3": 5.7, "12K5": 7.1, "14K1": 5.2, "14K3": 6.0, "14K4": 6.7, "14K6": 7.7,
    "16K2": 5.5, "16K3": 6.3, "16K4": 7.0, "16K5": 7.5, "16K6": 8.1, "16K7": 8.6, "16K9": 10.0,
    "18K3": 6.6, "18K4": 7.2, "18K5": 7.7, "18K6": 8.5, "18K7": 9.0, "18K9": 10.2, "18K10": 11.7,
    "20K3": 6.7, "20K4": 7.6, "20K5": 8.2, "20K6": 8.9, "20K7": 9.3, "20K9": 10.8, "20K10": 12.2,
    "22K4": 8.0, "22K5": 8.8, "22K6": 9.2, "22K7": 9.7, "22K9": 11.3, "22K10": 12.6, "22K11": 13.8,
    "24K4": 8.4, "24K5": 9.3, "24K6": 9.7, "24K7": 10.1, "24K8": 11.5, "24K9": 12.0, "24K10": 13.1, "24K12": 16.0,
    "26K5": 9.8, "26K6": 10.6, "26K7": 10.9, "26K8": 12.1, "26K9": 12.2, "26K10": 13.8, "26K12": 16.6,
    "28K6": 11.4, "28K7": 11.8, "28K8": 12.7, "28K9": 13.0, "28K10": 14.3, "28K12": 17.1,
    "30K7": 12.3, "30K8": 13.2, "30K9": 13.4, "30K10": 15.0, "30K11": 16.4, "30K12": 17.6,
    "18LH02": 10, "18LH03": 11, "18LH04": 12, "18LH05": 15, "18LH06": 15, "18LH07": 17, "18LH08": 19, "18LH09": 21,
    "20LH02": 10, "20LH03": 11, "20LH04": 12, "20LH05": 14, "20LH06": 15, "20LH07": 17, "20LH08": 19, "20LH09": 21, "20LH10": 23,
    "24LH03": 11, "24LH04": 12, "24LH05": 13, "24LH06": 16, "24LH07": 17, "24LH08": 18, "24LH09": 21, "24LH10": 23, "24LH11": 25,
    "28LH05": 13, "28LH06": 16, "28LH07": 17, "28LH08": 18, "28LH09": 21, "28LH10": 23, "28LH11": 25, "28LH12": 27, "28LH13": 30,
    "32LH06": 14, "32LH07": 16, "32LH08": 17, "32LH09": 21, "32LH10": 21, "32LH11": 24, "32LH12": 27, "32LH13": 30,
    "36LH07": 16, "36LH08": 18, "36LH09": 21, "36LH10": 21, "36LH11": 23, "36LH12": 25, "36LH13": 30, "36LH14": 36,
}


def find_callouts(text):
    """Yield (family, dims, raw) for every AISC-looking designation in text,
    plus ("JOIST", [designation], raw) for SJI joist designations."""
    t = clean(text)
    for m in CALLOUT.finditer(t):
        fam = m.group(1).upper()
        dims = [d.strip() for d in m.groups()[1:] if d]
        yield fam, dims, m.group(0)
    for m in JOIST.finditer(t):
        series = m.group(2) or m.group(4)
        section = m.group(3) if m.group(2) else m.group(5)
        desig = (m.group(1) + series + (section or "")).upper()
        yield "JOIST", [desig], m.group(0)


def resolve(fam, dims):
    """Return (key, confidence, note). key is the estimator's table key or None."""
    if fam == "JOIST":
        desig = dims[0].upper()
        if desig in JOIST_WEIGHTS:
            return desig, 1.0, ""
        return desig, 0.9, "joist weight from supplier (special / not in SJI approx table)"
    if fam == "PL":
        return None, 0.0, "plate callout (plates are not auto-counted)"
    if fam == "HP":
        return None, 0.0, "HP shape not in the estimator's shape table"
    db()
    cand = list(dims)
    if fam in ("L", "HSS") and len(cand) == 3:
        cand = [_to_fraction(c) for c in cand]
    key = norm(fam + "x".join(cand))
    if key in _INDEX:
        return _INDEX[key], 1.0, ""
    key2 = re.sub(r"\.0+(?=X|$)", "", key)          # "W8x21.0"
    if key2 in _INDEX:
        return _INDEX[key2], 0.95, "trailing .0 dropped"
    prefix = norm(fam + cand[0]) + "X"
    pool = [k for k in _INDEX if k.startswith(prefix)]
    close = difflib.get_close_matches(key, pool, n=2, cutoff=0.85)
    if len(close) == 1:
        return _INDEX[close[0]], 0.7, f"fuzzy from {fam} {' x '.join(dims)}"
    if len(close) > 1:
        return None, 0.0, "ambiguous: " + ", ".join(_INDEX[c] for c in close)
    return None, 0.0, "no such size in the estimator's shape table"


def weight(key):
    if key in JOIST_WEIGHTS:
        return JOIST_WEIGHTS[key]
    return db().get(key, {}).get("weight")


def category(key):
    if key in JOIST_WEIGHTS or JOIST.fullmatch(key or ""):
        return "Joist"
    return db().get(key, {}).get("category")


def all_weights():
    """{key: lb/ft} for every shape the sidecar can name (AISC table + joists)."""
    w = {k: v["weight"] for k, v in db().items()}
    w.update(JOIST_WEIGHTS)
    return w
