"""AISC callout matching against the estimator's own shape table
(sidecar/aisc-shapes.json, generated by scripts/export-aisc-shapes.mjs).

find_callouts(text) yields regex hits; resolve(fam, dims) turns a hit into the
estimator's key ('W8x21', 'HSS6x6x3/8') with a confidence, or None."""
import difflib
import json
import re
from fractions import Fraction
from pathlib import Path

_DB = None
_INDEX = None


def load_db(path=None):
    global _DB, _INDEX
    path = Path(path or Path(__file__).with_name("aisc-shapes.json"))
    _DB = json.loads(path.read_text())
    _INDEX = {norm(k): k for k in _DB}
    return _DB


def db():
    return _DB if _DB is not None else load_db()


_NUM = r"[0-9]+(?:\s*-\s*[0-9]+/[0-9]+|\s+[0-9]+/[0-9]+|/[0-9]+)?(?:\.[0-9]+)?|\.[0-9]+"
_SEP = r"\s*[xX\u00d7]\s*"
CALLOUT = re.compile(
    rf"(?<![A-Z0-9])(HSS|MC|WT|HP|PIPE|PL|W|C|L)\s*({_NUM}){_SEP}({_NUM})(?:{_SEP}({_NUM}))?(?![0-9/])",
    re.I,
)
_VULGAR = {"\u00bc": "1/4", "\u00bd": "1/2", "\u00be": "3/4", "\u215b": "1/8", "\u215c": "3/8",
           "\u215d": "5/8", "\u215e": "7/8", "\u2153": "1/3", "\u2154": "2/3"}


def clean(text):
    for k, v in _VULGAR.items():
        text = text.replace(k, " " + v)
    return text.replace("\u00d7", "x").replace("\u2013", "-").replace("\u2014", "-")


def norm(s):
    """Comparison form: upper, no whitespace."""
    return re.sub(r"\s+", "", clean(s)).upper()


def _to_fraction(tok):
    """'0.375' -> '3/8'; '3/8' stays; '1 1/2' -> '1-1/2'; '21' stays."""
    tok = tok.strip()
    if re.fullmatch(r"[0-9]*\.[0-9]+", tok):
        f = Fraction(tok).limit_denominator(16)
        if f.denominator == 1:
            return str(f.numerator)
        whole, rem = divmod(f.numerator, f.denominator)
        return f"{whole}-{rem}/{f.denominator}" if whole else f"{rem}/{f.denominator}"
    return re.sub(r"\s*-\s*|\s+", "-", tok)


def find_callouts(text):
    """Yield (family, dims, raw) for every AISC-looking designation in text."""
    for m in CALLOUT.finditer(clean(text)):
        fam = m.group(1).upper()
        dims = [d.strip() for d in m.groups()[1:] if d]
        yield fam, dims, m.group(0)


def resolve(fam, dims):
    """Return (key, confidence, note). key is the estimator's table key or None."""
    if fam == "PL":
        return None, 0.0, "plate callout (plates are not auto-counted)"
    if fam == "HP":
        return None, 0.0, "HP shape not in the estimator's shape table"
    db()
    cand = list(dims)
    if fam in ("L", "HSS") and len(cand) == 3:
        cand = [_to_fraction(c) for c in cand]
    key = norm(fam + "x".join(cand))
    if key in _INDEX:
        return _INDEX[key], 1.0, ""
    key2 = re.sub(r"\.0+(?=X|$)", "", key)          # "W8x21.0"
    if key2 in _INDEX:
        return _INDEX[key2], 0.95, "trailing .0 dropped"
    prefix = norm(fam + cand[0]) + "X"
    pool = [k for k in _INDEX if k.startswith(prefix)]
    close = difflib.get_close_matches(key, pool, n=2, cutoff=0.85)
    if len(close) == 1:
        return _INDEX[close[0]], 0.7, f"fuzzy from {fam} {' x '.join(dims)}"
    if len(close) > 1:
        return None, 0.0, "ambiguous: " + ", ".join(_INDEX[c] for c in close)
    return None, 0.0, "no such size in the estimator's shape table"


def weight(key):
    return db().get(key, {}).get("weight")


def category(key):
    return db().get(key, {}).get("category")
