import { sql } from "drizzle-orm";
import { pgTable, text, varchar, integer, real, boolean, jsonb, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const projects = pgTable("projects", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  customerCompany: text("customer_company").default(""),
  customerContact: text("customer_contact").default(""),
  customerAddress: text("customer_address").default(""),
  customerPhone: text("customer_phone").default(""),
  customerEmail: text("customer_email").default(""),
  projectName: text("project_name").notNull(),
  projectAddress: text("project_address").default(""),
  drawingDate: text("drawing_date").default(""),
  drawingRevision: text("drawing_revision").default(""),
  architect: text("architect").default(""),
  estimateDate: text("estimate_date").default(""),
  estimatedBy: text("estimated_by").default(""),
  projectType: text("project_type").default("structural"),
  deliveryOption: text("delivery_option").default("installed"),
  taxCategory: text("tax_category").default("new_construction"),
  exclusions: jsonb("exclusions").$type<string[]>().default([]),
  qualifications: jsonb("qualifications").$type<string[]>().default([]),
  status: text("status").default("draft"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const estimateItems = pgTable("estimate_items", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  projectId: integer("project_id").notNull(),
  name: text("name").notNull(),
  description: text("description").default(""),
  drawingRef: text("drawing_ref").default(""),
  breakoutGroup: text("breakout_group").default("base"),
  materialMarkupPercent: real("material_markup_percent").default(0),
  fabMarkupPercent: real("fab_markup_percent").default(0),
  generalFabOps: jsonb("general_fab_ops").$type<FabOperation[]>().default([]),
  sortOrder: integer("sort_order").default(0),
});

export const materials = pgTable("materials", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  itemId: integer("item_id").notNull(),
  shapeCategory: text("shape_category").notNull(),
  shape: text("shape").notNull(),
  weightPerFoot: real("weight_per_foot").default(0),
  length: real("length").default(0),
  quantity: integer("quantity").default(1),
  unitPrice: real("unit_price").default(0),
  stockLength: real("stock_length").default(20),
  galvanized: boolean("galvanized").default(false),
  parentMaterialId: integer("parent_material_id"),
  fabOps: jsonb("fab_ops").$type<FabOperation[]>().default([]),
  sortOrder: integer("sort_order").default(0),
});

export const recapCosts = pgTable("recap_costs", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  itemId: integer("item_id").notNull(),
  installationHours: real("installation_hours").default(0),
  installationRate: real("installation_rate").default(0),
  draftingHours: real("drafting_hours").default(0),
  draftingRate: real("drafting_rate").default(0),
  engineeringHours: real("engineering_hours").default(0),
  engineeringRate: real("engineering_rate").default(0),
  projectMgmtHours: real("project_mgmt_hours").default(0),
  projectMgmtRate: real("project_mgmt_rate").default(0),
  shippingCost: real("shipping_cost").default(0),
  markupPercent: real("markup_percent").default(0),
  customCosts: jsonb("custom_costs").$type<CustomCost[]>().default([]),
});

export const summaryAdjustments = pgTable("summary_adjustments", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  projectId: integer("project_id").notNull(),
  description: text("description").notNull(),
  amount: real("amount").default(0),
  sortOrder: integer("sort_order").default(0),
});

export interface FabOperation {
  id: string;
  category: string;
  name: string;
  hours: number;
  rate: number;
  cost: number;
}

export interface CustomCost {
  id: string;
  name: string;
  hours: number;
  rate: number;
  amount: number;
  markupPercent: number;
}

export const insertProjectSchema = createInsertSchema(projects).omit({ id: true, createdAt: true, updatedAt: true });
export const insertEstimateItemSchema = createInsertSchema(estimateItems).omit({ id: true });
export const insertMaterialSchema = createInsertSchema(materials).omit({ id: true });
export const insertRecapCostSchema = createInsertSchema(recapCosts).omit({ id: true });
export const insertSummaryAdjustmentSchema = createInsertSchema(summaryAdjustments).omit({ id: true });

export type InsertProject = z.infer<typeof insertProjectSchema>;
export type Project = typeof projects.$inferSelect;
export type InsertEstimateItem = z.infer<typeof insertEstimateItemSchema>;
export type EstimateItem = typeof estimateItems.$inferSelect;
export type InsertMaterial = z.infer<typeof insertMaterialSchema>;
export type Material = typeof materials.$inferSelect;
export type InsertRecapCost = z.infer<typeof insertRecapCostSchema>;
export type RecapCost = typeof recapCosts.$inferSelect;
export type InsertSummaryAdjustment = z.infer<typeof insertSummaryAdjustmentSchema>;
export type SummaryAdjustment = typeof summaryAdjustments.$inferSelect;

export const TAX_CATEGORIES = {
  new_construction: { label: "New Construction", rate: 0.0825, description: "8.25% on materials only", appliesTo: ["materials"] },
  resale: { label: "Resale", rate: 0, description: "No tax — buyer provides resale certificate", appliesTo: [] },
  fob: { label: "F.O.B.", rate: 0.0825, description: "8.25% on materials + fabrication", appliesTo: ["materials", "fabrication"] },
  no_tax: { label: "No Tax", rate: 0, description: "Exempt entities", appliesTo: [] },
} as const;

export const PROJECT_TYPES = ["Structural", "Miscellaneous", "Ornamental"] as const;
export const DELIVERY_OPTIONS = ["Installed", "F.O.B. Jobsite", "Will Call"] as const;
export const BREAKOUT_GROUPS = ["Base", "Deduct", "Add"] as const;

export const STANDARD_EXCLUSIONS = [
  "Anchor bolts by others",
  "Engineering and shop drawings by others",
  "Field welding by others",
  "Fireproofing by others",
  "Galvanizing unless noted",
  "Metal deck by others",
  "Open web steel joists by others",
  "Painting by others unless noted",
  "Permits by others",
  "Shoring and bracing by others",
];

export const STANDARD_QUALIFICATIONS = [
  "Based on drawings and specifications provided",
  "Prices valid for 30 days",
  "Standard shop coat included unless noted otherwise",
  "Fabrication per AISC standards",
  "All structural calculations by others",
  "Normal working hours — overtime not included",
  "Access to job site assumed clear and level",
];

export const FAB_CATEGORIES = {
  coatings: [
    "Prime Paint", "Blast & Prime", "Finish Paint", "TNEMEC",
    "Specialty Coating", "Std. Shop Coat", "Anodized", "Powder Coat", "Glass Bead Blast"
  ],
  finishes: ["#4 Satin", "#8 Mirror", "Non-Directional", "Specialty Finish"],
  handling: ["Handling", "Fit up/Assembly", "Shop Inspection", "Shop Load-out", "Hotshot"],
  connections: [
    "Shear Tab", "Clip Angle", "End Plate", "Base Plate", "Cap Plate",
    "Gusset Plate", "Stiffener Plate", "Cope", "Weld", "Bolt Holes"
  ],
};

export interface SteelShape {
  category: string;
  name: string;
  weightPerFoot: number;
  depth?: number;
}

export const STEEL_SHAPES: SteelShape[] = [
  // W Shapes (Wide Flange)
  { category: "W", name: "W4x13", weightPerFoot: 13 },
  { category: "W", name: "W6x9", weightPerFoot: 9 },
  { category: "W", name: "W6x12", weightPerFoot: 12 },
  { category: "W", name: "W6x15", weightPerFoot: 15 },
  { category: "W", name: "W6x20", weightPerFoot: 20 },
  { category: "W", name: "W6x25", weightPerFoot: 25 },
  { category: "W", name: "W8x10", weightPerFoot: 10 },
  { category: "W", name: "W8x13", weightPerFoot: 13 },
  { category: "W", name: "W8x15", weightPerFoot: 15 },
  { category: "W", name: "W8x18", weightPerFoot: 18 },
  { category: "W", name: "W8x21", weightPerFoot: 21 },
  { category: "W", name: "W8x24", weightPerFoot: 24 },
  { category: "W", name: "W8x28", weightPerFoot: 28 },
  { category: "W", name: "W8x31", weightPerFoot: 31 },
  { category: "W", name: "W8x35", weightPerFoot: 35 },
  { category: "W", name: "W8x40", weightPerFoot: 40 },
  { category: "W", name: "W8x48", weightPerFoot: 48 },
  { category: "W", name: "W8x58", weightPerFoot: 58 },
  { category: "W", name: "W8x67", weightPerFoot: 67 },
  { category: "W", name: "W10x12", weightPerFoot: 12 },
  { category: "W", name: "W10x15", weightPerFoot: 15 },
  { category: "W", name: "W10x17", weightPerFoot: 17 },
  { category: "W", name: "W10x19", weightPerFoot: 19 },
  { category: "W", name: "W10x22", weightPerFoot: 22 },
  { category: "W", name: "W10x26", weightPerFoot: 26 },
  { category: "W", name: "W10x30", weightPerFoot: 30 },
  { category: "W", name: "W10x33", weightPerFoot: 33 },
  { category: "W", name: "W10x39", weightPerFoot: 39 },
  { category: "W", name: "W10x45", weightPerFoot: 45 },
  { category: "W", name: "W10x49", weightPerFoot: 49 },
  { category: "W", name: "W10x54", weightPerFoot: 54 },
  { category: "W", name: "W10x60", weightPerFoot: 60 },
  { category: "W", name: "W10x68", weightPerFoot: 68 },
  { category: "W", name: "W10x77", weightPerFoot: 77 },
  { category: "W", name: "W10x88", weightPerFoot: 88 },
  { category: "W", name: "W10x100", weightPerFoot: 100 },
  { category: "W", name: "W10x112", weightPerFoot: 112 },
  { category: "W", name: "W12x14", weightPerFoot: 14 },
  { category: "W", name: "W12x16", weightPerFoot: 16 },
  { category: "W", name: "W12x19", weightPerFoot: 19 },
  { category: "W", name: "W12x22", weightPerFoot: 22 },
  { category: "W", name: "W12x26", weightPerFoot: 26 },
  { category: "W", name: "W12x30", weightPerFoot: 30 },
  { category: "W", name: "W12x35", weightPerFoot: 35 },
  { category: "W", name: "W12x40", weightPerFoot: 40 },
  { category: "W", name: "W12x45", weightPerFoot: 45 },
  { category: "W", name: "W12x50", weightPerFoot: 50 },
  { category: "W", name: "W12x53", weightPerFoot: 53 },
  { category: "W", name: "W12x58", weightPerFoot: 58 },
  { category: "W", name: "W12x65", weightPerFoot: 65 },
  { category: "W", name: "W12x72", weightPerFoot: 72 },
  { category: "W", name: "W12x79", weightPerFoot: 79 },
  { category: "W", name: "W12x87", weightPerFoot: 87 },
  { category: "W", name: "W12x96", weightPerFoot: 96 },
  { category: "W", name: "W12x106", weightPerFoot: 106 },
  { category: "W", name: "W12x120", weightPerFoot: 120 },
  { category: "W", name: "W12x136", weightPerFoot: 136 },
  { category: "W", name: "W12x152", weightPerFoot: 152 },
  { category: "W", name: "W12x170", weightPerFoot: 170 },
  { category: "W", name: "W12x190", weightPerFoot: 190 },
  { category: "W", name: "W14x22", weightPerFoot: 22 },
  { category: "W", name: "W14x26", weightPerFoot: 26 },
  { category: "W", name: "W14x30", weightPerFoot: 30 },
  { category: "W", name: "W14x34", weightPerFoot: 34 },
  { category: "W", name: "W14x38", weightPerFoot: 38 },
  { category: "W", name: "W14x43", weightPerFoot: 43 },
  { category: "W", name: "W14x48", weightPerFoot: 48 },
  { category: "W", name: "W14x53", weightPerFoot: 53 },
  { category: "W", name: "W14x61", weightPerFoot: 61 },
  { category: "W", name: "W14x68", weightPerFoot: 68 },
  { category: "W", name: "W14x74", weightPerFoot: 74 },
  { category: "W", name: "W14x82", weightPerFoot: 82 },
  { category: "W", name: "W14x90", weightPerFoot: 90 },
  { category: "W", name: "W14x99", weightPerFoot: 99 },
  { category: "W", name: "W14x109", weightPerFoot: 109 },
  { category: "W", name: "W14x120", weightPerFoot: 120 },
  { category: "W", name: "W14x132", weightPerFoot: 132 },
  { category: "W", name: "W16x26", weightPerFoot: 26 },
  { category: "W", name: "W16x31", weightPerFoot: 31 },
  { category: "W", name: "W16x36", weightPerFoot: 36 },
  { category: "W", name: "W16x40", weightPerFoot: 40 },
  { category: "W", name: "W16x45", weightPerFoot: 45 },
  { category: "W", name: "W16x50", weightPerFoot: 50 },
  { category: "W", name: "W16x57", weightPerFoot: 57 },
  { category: "W", name: "W16x67", weightPerFoot: 67 },
  { category: "W", name: "W16x77", weightPerFoot: 77 },
  { category: "W", name: "W16x89", weightPerFoot: 89 },
  { category: "W", name: "W16x100", weightPerFoot: 100 },
  { category: "W", name: "W18x35", weightPerFoot: 35 },
  { category: "W", name: "W18x40", weightPerFoot: 40 },
  { category: "W", name: "W18x46", weightPerFoot: 46 },
  { category: "W", name: "W18x50", weightPerFoot: 50 },
  { category: "W", name: "W18x55", weightPerFoot: 55 },
  { category: "W", name: "W18x60", weightPerFoot: 60 },
  { category: "W", name: "W18x65", weightPerFoot: 65 },
  { category: "W", name: "W18x71", weightPerFoot: 71 },
  { category: "W", name: "W18x76", weightPerFoot: 76 },
  { category: "W", name: "W18x86", weightPerFoot: 86 },
  { category: "W", name: "W18x97", weightPerFoot: 97 },
  { category: "W", name: "W18x106", weightPerFoot: 106 },
  { category: "W", name: "W21x44", weightPerFoot: 44 },
  { category: "W", name: "W21x50", weightPerFoot: 50 },
  { category: "W", name: "W21x57", weightPerFoot: 57 },
  { category: "W", name: "W21x62", weightPerFoot: 62 },
  { category: "W", name: "W21x68", weightPerFoot: 68 },
  { category: "W", name: "W21x73", weightPerFoot: 73 },
  { category: "W", name: "W21x83", weightPerFoot: 83 },
  { category: "W", name: "W21x93", weightPerFoot: 93 },
  { category: "W", name: "W21x101", weightPerFoot: 101 },
  { category: "W", name: "W21x111", weightPerFoot: 111 },
  { category: "W", name: "W21x122", weightPerFoot: 122 },
  { category: "W", name: "W21x132", weightPerFoot: 132 },
  { category: "W", name: "W24x55", weightPerFoot: 55 },
  { category: "W", name: "W24x62", weightPerFoot: 62 },
  { category: "W", name: "W24x68", weightPerFoot: 68 },
  { category: "W", name: "W24x76", weightPerFoot: 76 },
  { category: "W", name: "W24x84", weightPerFoot: 84 },
  { category: "W", name: "W24x94", weightPerFoot: 94 },
  { category: "W", name: "W24x104", weightPerFoot: 104 },
  { category: "W", name: "W24x117", weightPerFoot: 117 },
  { category: "W", name: "W24x131", weightPerFoot: 131 },
  { category: "W", name: "W24x146", weightPerFoot: 146 },
  { category: "W", name: "W24x162", weightPerFoot: 162 },
  { category: "W", name: "W27x84", weightPerFoot: 84 },
  { category: "W", name: "W27x94", weightPerFoot: 94 },
  { category: "W", name: "W27x102", weightPerFoot: 102 },
  { category: "W", name: "W27x114", weightPerFoot: 114 },
  { category: "W", name: "W27x129", weightPerFoot: 129 },
  { category: "W", name: "W27x146", weightPerFoot: 146 },
  { category: "W", name: "W27x161", weightPerFoot: 161 },
  { category: "W", name: "W30x90", weightPerFoot: 90 },
  { category: "W", name: "W30x99", weightPerFoot: 99 },
  { category: "W", name: "W30x108", weightPerFoot: 108 },
  { category: "W", name: "W30x116", weightPerFoot: 116 },
  { category: "W", name: "W30x124", weightPerFoot: 124 },
  { category: "W", name: "W30x132", weightPerFoot: 132 },
  { category: "W", name: "W30x148", weightPerFoot: 148 },
  { category: "W", name: "W33x118", weightPerFoot: 118 },
  { category: "W", name: "W33x130", weightPerFoot: 130 },
  { category: "W", name: "W33x141", weightPerFoot: 141 },
  { category: "W", name: "W33x152", weightPerFoot: 152 },
  { category: "W", name: "W36x135", weightPerFoot: 135 },
  { category: "W", name: "W36x150", weightPerFoot: 150 },
  { category: "W", name: "W36x160", weightPerFoot: 160 },
  { category: "W", name: "W36x170", weightPerFoot: 170 },
  { category: "W", name: "W36x182", weightPerFoot: 182 },
  { category: "W", name: "W36x194", weightPerFoot: 194 },
  { category: "W", name: "W36x210", weightPerFoot: 210 },
  { category: "W", name: "W36x232", weightPerFoot: 232 },
  { category: "W", name: "W36x256", weightPerFoot: 256 },
  // HSS (Hollow Structural Sections - Square/Rectangular)
  { category: "HSS", name: "HSS2x2x3/16", weightPerFoot: 4.32 },
  { category: "HSS", name: "HSS2x2x1/4", weightPerFoot: 5.41 },
  { category: "HSS", name: "HSS2-1/2x2-1/2x3/16", weightPerFoot: 5.59 },
  { category: "HSS", name: "HSS2-1/2x2-1/2x1/4", weightPerFoot: 7.11 },
  { category: "HSS", name: "HSS3x3x3/16", weightPerFoot: 6.87 },
  { category: "HSS", name: "HSS3x3x1/4", weightPerFoot: 8.81 },
  { category: "HSS", name: "HSS3x3x5/16", weightPerFoot: 10.58 },
  { category: "HSS", name: "HSS3x3x3/8", weightPerFoot: 12.17 },
  { category: "HSS", name: "HSS4x4x3/16", weightPerFoot: 9.42 },
  { category: "HSS", name: "HSS4x4x1/4", weightPerFoot: 12.21 },
  { category: "HSS", name: "HSS4x4x5/16", weightPerFoot: 14.83 },
  { category: "HSS", name: "HSS4x4x3/8", weightPerFoot: 17.27 },
  { category: "HSS", name: "HSS4x4x1/2", weightPerFoot: 21.63 },
  { category: "HSS", name: "HSS5x5x3/16", weightPerFoot: 11.97 },
  { category: "HSS", name: "HSS5x5x1/4", weightPerFoot: 15.62 },
  { category: "HSS", name: "HSS5x5x5/16", weightPerFoot: 19.08 },
  { category: "HSS", name: "HSS5x5x3/8", weightPerFoot: 22.37 },
  { category: "HSS", name: "HSS5x5x1/2", weightPerFoot: 28.43 },
  { category: "HSS", name: "HSS6x6x3/16", weightPerFoot: 14.53 },
  { category: "HSS", name: "HSS6x6x1/4", weightPerFoot: 19.02 },
  { category: "HSS", name: "HSS6x6x5/16", weightPerFoot: 23.34 },
  { category: "HSS", name: "HSS6x6x3/8", weightPerFoot: 27.48 },
  { category: "HSS", name: "HSS6x6x1/2", weightPerFoot: 35.24 },
  { category: "HSS", name: "HSS6x6x5/8", weightPerFoot: 42.30 },
  { category: "HSS", name: "HSS8x8x1/4", weightPerFoot: 25.82 },
  { category: "HSS", name: "HSS8x8x5/16", weightPerFoot: 31.84 },
  { category: "HSS", name: "HSS8x8x3/8", weightPerFoot: 37.69 },
  { category: "HSS", name: "HSS8x8x1/2", weightPerFoot: 48.85 },
  { category: "HSS", name: "HSS8x8x5/8", weightPerFoot: 59.32 },
  { category: "HSS", name: "HSS10x10x1/4", weightPerFoot: 32.63 },
  { category: "HSS", name: "HSS10x10x3/8", weightPerFoot: 47.90 },
  { category: "HSS", name: "HSS10x10x1/2", weightPerFoot: 62.46 },
  { category: "HSS", name: "HSS10x10x5/8", weightPerFoot: 76.33 },
  { category: "HSS", name: "HSS12x12x3/8", weightPerFoot: 58.10 },
  { category: "HSS", name: "HSS12x12x1/2", weightPerFoot: 76.07 },
  { category: "HSS", name: "HSS12x12x5/8", weightPerFoot: 93.34 },
  // HSS Rectangular
  { category: "HSS", name: "HSS4x2x3/16", weightPerFoot: 6.87 },
  { category: "HSS", name: "HSS4x2x1/4", weightPerFoot: 8.81 },
  { category: "HSS", name: "HSS4x2x3/8", weightPerFoot: 12.17 },
  { category: "HSS", name: "HSS6x2x1/4", weightPerFoot: 12.21 },
  { category: "HSS", name: "HSS6x2x3/8", weightPerFoot: 17.27 },
  { category: "HSS", name: "HSS6x3x1/4", weightPerFoot: 13.91 },
  { category: "HSS", name: "HSS6x3x3/8", weightPerFoot: 19.82 },
  { category: "HSS", name: "HSS6x4x1/4", weightPerFoot: 15.62 },
  { category: "HSS", name: "HSS6x4x3/8", weightPerFoot: 22.37 },
  { category: "HSS", name: "HSS8x4x1/4", weightPerFoot: 19.02 },
  { category: "HSS", name: "HSS8x4x3/8", weightPerFoot: 27.48 },
  { category: "HSS", name: "HSS8x4x1/2", weightPerFoot: 35.24 },
  { category: "HSS", name: "HSS8x6x1/4", weightPerFoot: 22.42 },
  { category: "HSS", name: "HSS8x6x3/8", weightPerFoot: 32.58 },
  { category: "HSS", name: "HSS8x6x1/2", weightPerFoot: 42.05 },
  { category: "HSS", name: "HSS10x6x1/4", weightPerFoot: 25.82 },
  { category: "HSS", name: "HSS10x6x3/8", weightPerFoot: 37.69 },
  { category: "HSS", name: "HSS10x6x1/2", weightPerFoot: 48.85 },
  // Pipe
  { category: "Pipe", name: "Pipe 1/2 Std", weightPerFoot: 0.85 },
  { category: "Pipe", name: "Pipe 3/4 Std", weightPerFoot: 1.13 },
  { category: "Pipe", name: "Pipe 1 Std", weightPerFoot: 1.68 },
  { category: "Pipe", name: "Pipe 1-1/4 Std", weightPerFoot: 2.27 },
  { category: "Pipe", name: "Pipe 1-1/2 Std", weightPerFoot: 2.72 },
  { category: "Pipe", name: "Pipe 2 Std", weightPerFoot: 3.65 },
  { category: "Pipe", name: "Pipe 2-1/2 Std", weightPerFoot: 5.79 },
  { category: "Pipe", name: "Pipe 3 Std", weightPerFoot: 7.58 },
  { category: "Pipe", name: "Pipe 3-1/2 Std", weightPerFoot: 9.11 },
  { category: "Pipe", name: "Pipe 4 Std", weightPerFoot: 10.79 },
  { category: "Pipe", name: "Pipe 5 Std", weightPerFoot: 14.62 },
  { category: "Pipe", name: "Pipe 6 Std", weightPerFoot: 18.97 },
  { category: "Pipe", name: "Pipe 8 Std", weightPerFoot: 28.55 },
  { category: "Pipe", name: "Pipe 10 Std", weightPerFoot: 40.48 },
  { category: "Pipe", name: "Pipe 12 Std", weightPerFoot: 49.56 },
  { category: "Pipe", name: "Pipe 1 XS", weightPerFoot: 2.17 },
  { category: "Pipe", name: "Pipe 1-1/2 XS", weightPerFoot: 3.63 },
  { category: "Pipe", name: "Pipe 2 XS", weightPerFoot: 5.02 },
  { category: "Pipe", name: "Pipe 3 XS", weightPerFoot: 10.25 },
  { category: "Pipe", name: "Pipe 4 XS", weightPerFoot: 14.98 },
  { category: "Pipe", name: "Pipe 6 XS", weightPerFoot: 28.57 },
  { category: "Pipe", name: "Pipe 8 XS", weightPerFoot: 43.39 },
  // Angle (L shapes)
  { category: "Angle", name: "L2x2x1/8", weightPerFoot: 1.65 },
  { category: "Angle", name: "L2x2x3/16", weightPerFoot: 2.44 },
  { category: "Angle", name: "L2x2x1/4", weightPerFoot: 3.19 },
  { category: "Angle", name: "L2x2x5/16", weightPerFoot: 3.92 },
  { category: "Angle", name: "L2x2x3/8", weightPerFoot: 4.70 },
  { category: "Angle", name: "L2-1/2x2-1/2x3/16", weightPerFoot: 3.07 },
  { category: "Angle", name: "L2-1/2x2-1/2x1/4", weightPerFoot: 4.10 },
  { category: "Angle", name: "L2-1/2x2-1/2x5/16", weightPerFoot: 5.00 },
  { category: "Angle", name: "L2-1/2x2-1/2x3/8", weightPerFoot: 5.90 },
  { category: "Angle", name: "L3x3x3/16", weightPerFoot: 3.71 },
  { category: "Angle", name: "L3x3x1/4", weightPerFoot: 4.90 },
  { category: "Angle", name: "L3x3x5/16", weightPerFoot: 6.10 },
  { category: "Angle", name: "L3x3x3/8", weightPerFoot: 7.20 },
  { category: "Angle", name: "L3x3x1/2", weightPerFoot: 9.40 },
  { category: "Angle", name: "L3-1/2x3-1/2x1/4", weightPerFoot: 5.80 },
  { category: "Angle", name: "L3-1/2x3-1/2x5/16", weightPerFoot: 7.20 },
  { category: "Angle", name: "L3-1/2x3-1/2x3/8", weightPerFoot: 8.50 },
  { category: "Angle", name: "L3-1/2x3-1/2x1/2", weightPerFoot: 11.10 },
  { category: "Angle", name: "L4x4x1/4", weightPerFoot: 6.60 },
  { category: "Angle", name: "L4x4x5/16", weightPerFoot: 8.20 },
  { category: "Angle", name: "L4x4x3/8", weightPerFoot: 9.80 },
  { category: "Angle", name: "L4x4x1/2", weightPerFoot: 12.80 },
  { category: "Angle", name: "L4x4x5/8", weightPerFoot: 15.70 },
  { category: "Angle", name: "L5x5x5/16", weightPerFoot: 10.30 },
  { category: "Angle", name: "L5x5x3/8", weightPerFoot: 12.30 },
  { category: "Angle", name: "L5x5x1/2", weightPerFoot: 16.20 },
  { category: "Angle", name: "L5x5x5/8", weightPerFoot: 20.00 },
  { category: "Angle", name: "L6x6x3/8", weightPerFoot: 14.90 },
  { category: "Angle", name: "L6x6x1/2", weightPerFoot: 19.60 },
  { category: "Angle", name: "L6x6x5/8", weightPerFoot: 24.20 },
  { category: "Angle", name: "L6x6x3/4", weightPerFoot: 28.70 },
  { category: "Angle", name: "L8x8x1/2", weightPerFoot: 26.40 },
  { category: "Angle", name: "L8x8x5/8", weightPerFoot: 32.70 },
  { category: "Angle", name: "L8x8x3/4", weightPerFoot: 38.90 },
  { category: "Angle", name: "L8x8x1", weightPerFoot: 51.00 },
  // Unequal Angles
  { category: "Angle", name: "L3x2x1/4", weightPerFoot: 4.10 },
  { category: "Angle", name: "L3x2x3/8", weightPerFoot: 5.90 },
  { category: "Angle", name: "L4x3x1/4", weightPerFoot: 5.80 },
  { category: "Angle", name: "L4x3x3/8", weightPerFoot: 8.50 },
  { category: "Angle", name: "L4x3x1/2", weightPerFoot: 11.10 },
  { category: "Angle", name: "L5x3x1/4", weightPerFoot: 6.60 },
  { category: "Angle", name: "L5x3x3/8", weightPerFoot: 9.80 },
  { category: "Angle", name: "L5x3x1/2", weightPerFoot: 12.80 },
  { category: "Angle", name: "L6x4x3/8", weightPerFoot: 12.30 },
  { category: "Angle", name: "L6x4x1/2", weightPerFoot: 16.20 },
  { category: "Angle", name: "L6x4x5/8", weightPerFoot: 20.00 },
  { category: "Angle", name: "L7x4x3/8", weightPerFoot: 13.60 },
  { category: "Angle", name: "L7x4x1/2", weightPerFoot: 17.90 },
  { category: "Angle", name: "L8x6x1/2", weightPerFoot: 23.00 },
  { category: "Angle", name: "L8x6x5/8", weightPerFoot: 28.50 },
  // Channel (C shapes)
  { category: "Channel", name: "C3x4.1", weightPerFoot: 4.1 },
  { category: "Channel", name: "C3x5", weightPerFoot: 5 },
  { category: "Channel", name: "C3x6", weightPerFoot: 6 },
  { category: "Channel", name: "C4x5.4", weightPerFoot: 5.4 },
  { category: "Channel", name: "C4x7.25", weightPerFoot: 7.25 },
  { category: "Channel", name: "C5x6.7", weightPerFoot: 6.7 },
  { category: "Channel", name: "C5x9", weightPerFoot: 9 },
  { category: "Channel", name: "C6x8.2", weightPerFoot: 8.2 },
  { category: "Channel", name: "C6x10.5", weightPerFoot: 10.5 },
  { category: "Channel", name: "C6x13", weightPerFoot: 13 },
  { category: "Channel", name: "C7x9.8", weightPerFoot: 9.8 },
  { category: "Channel", name: "C7x12.25", weightPerFoot: 12.25 },
  { category: "Channel", name: "C7x14.75", weightPerFoot: 14.75 },
  { category: "Channel", name: "C8x11.5", weightPerFoot: 11.5 },
  { category: "Channel", name: "C8x13.75", weightPerFoot: 13.75 },
  { category: "Channel", name: "C8x18.75", weightPerFoot: 18.75 },
  { category: "Channel", name: "C9x13.4", weightPerFoot: 13.4 },
  { category: "Channel", name: "C9x15", weightPerFoot: 15 },
  { category: "Channel", name: "C9x20", weightPerFoot: 20 },
  { category: "Channel", name: "C10x15.3", weightPerFoot: 15.3 },
  { category: "Channel", name: "C10x20", weightPerFoot: 20 },
  { category: "Channel", name: "C10x25", weightPerFoot: 25 },
  { category: "Channel", name: "C10x30", weightPerFoot: 30 },
  { category: "Channel", name: "C12x20.7", weightPerFoot: 20.7 },
  { category: "Channel", name: "C12x25", weightPerFoot: 25 },
  { category: "Channel", name: "C12x30", weightPerFoot: 30 },
  { category: "Channel", name: "C15x33.9", weightPerFoot: 33.9 },
  { category: "Channel", name: "C15x40", weightPerFoot: 40 },
  { category: "Channel", name: "C15x50", weightPerFoot: 50 },
  // MC (Miscellaneous Channels)
  { category: "Channel", name: "MC6x12", weightPerFoot: 12 },
  { category: "Channel", name: "MC6x15.3", weightPerFoot: 15.3 },
  { category: "Channel", name: "MC6x16.3", weightPerFoot: 16.3 },
  { category: "Channel", name: "MC8x8.5", weightPerFoot: 8.5 },
  { category: "Channel", name: "MC8x20", weightPerFoot: 20 },
  { category: "Channel", name: "MC8x22.8", weightPerFoot: 22.8 },
  { category: "Channel", name: "MC10x6.5", weightPerFoot: 6.5 },
  { category: "Channel", name: "MC10x22", weightPerFoot: 22 },
  { category: "Channel", name: "MC10x28.5", weightPerFoot: 28.5 },
  { category: "Channel", name: "MC12x10.6", weightPerFoot: 10.6 },
  { category: "Channel", name: "MC12x31", weightPerFoot: 31 },
  { category: "Channel", name: "MC12x35", weightPerFoot: 35 },
  // Flat Bar
  { category: "Flat Bar", name: "FB 1/8x1", weightPerFoot: 0.43 },
  { category: "Flat Bar", name: "FB 1/8x1-1/2", weightPerFoot: 0.64 },
  { category: "Flat Bar", name: "FB 1/8x2", weightPerFoot: 0.85 },
  { category: "Flat Bar", name: "FB 3/16x1", weightPerFoot: 0.64 },
  { category: "Flat Bar", name: "FB 3/16x1-1/2", weightPerFoot: 0.96 },
  { category: "Flat Bar", name: "FB 3/16x2", weightPerFoot: 1.28 },
  { category: "Flat Bar", name: "FB 1/4x1", weightPerFoot: 0.85 },
  { category: "Flat Bar", name: "FB 1/4x1-1/2", weightPerFoot: 1.28 },
  { category: "Flat Bar", name: "FB 1/4x2", weightPerFoot: 1.70 },
  { category: "Flat Bar", name: "FB 1/4x2-1/2", weightPerFoot: 2.13 },
  { category: "Flat Bar", name: "FB 1/4x3", weightPerFoot: 2.55 },
  { category: "Flat Bar", name: "FB 1/4x4", weightPerFoot: 3.40 },
  { category: "Flat Bar", name: "FB 1/4x5", weightPerFoot: 4.25 },
  { category: "Flat Bar", name: "FB 1/4x6", weightPerFoot: 5.10 },
  { category: "Flat Bar", name: "FB 3/8x2", weightPerFoot: 2.55 },
  { category: "Flat Bar", name: "FB 3/8x3", weightPerFoot: 3.83 },
  { category: "Flat Bar", name: "FB 3/8x4", weightPerFoot: 5.10 },
  { category: "Flat Bar", name: "FB 3/8x5", weightPerFoot: 6.38 },
  { category: "Flat Bar", name: "FB 3/8x6", weightPerFoot: 7.65 },
  { category: "Flat Bar", name: "FB 1/2x2", weightPerFoot: 3.40 },
  { category: "Flat Bar", name: "FB 1/2x3", weightPerFoot: 5.10 },
  { category: "Flat Bar", name: "FB 1/2x4", weightPerFoot: 6.80 },
  { category: "Flat Bar", name: "FB 1/2x5", weightPerFoot: 8.50 },
  { category: "Flat Bar", name: "FB 1/2x6", weightPerFoot: 10.20 },
  { category: "Flat Bar", name: "FB 1/2x8", weightPerFoot: 13.60 },
  { category: "Flat Bar", name: "FB 5/8x4", weightPerFoot: 8.50 },
  { category: "Flat Bar", name: "FB 5/8x6", weightPerFoot: 12.75 },
  { category: "Flat Bar", name: "FB 3/4x4", weightPerFoot: 10.20 },
  { category: "Flat Bar", name: "FB 3/4x6", weightPerFoot: 15.30 },
  { category: "Flat Bar", name: "FB 1x4", weightPerFoot: 13.60 },
  { category: "Flat Bar", name: "FB 1x6", weightPerFoot: 20.40 },
  { category: "Flat Bar", name: "FB 1x8", weightPerFoot: 27.20 },
  // Plate
  { category: "Plate", name: "PL 1/4", weightPerFoot: 10.21 },
  { category: "Plate", name: "PL 5/16", weightPerFoot: 12.76 },
  { category: "Plate", name: "PL 3/8", weightPerFoot: 15.31 },
  { category: "Plate", name: "PL 1/2", weightPerFoot: 20.41 },
  { category: "Plate", name: "PL 5/8", weightPerFoot: 25.51 },
  { category: "Plate", name: "PL 3/4", weightPerFoot: 30.61 },
  { category: "Plate", name: "PL 7/8", weightPerFoot: 35.71 },
  { category: "Plate", name: "PL 1", weightPerFoot: 40.80 },
  { category: "Plate", name: "PL 1-1/4", weightPerFoot: 51.00 },
  { category: "Plate", name: "PL 1-1/2", weightPerFoot: 61.20 },
  { category: "Plate", name: "PL 2", weightPerFoot: 81.60 },
];
